// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by generator, DO NOT EDIT.
package version

var (
	Latest = v8_17_0
	Index  = map[string]map[string]*Field{
		"1.0":    v1_0_1,
		"1.0.1":  v1_0_1,
		"1.1":    v1_1_0,
		"1.1.0":  v1_1_0,
		"1.2":    v1_2_0,
		"1.2.0":  v1_2_0,
		"1.3.0":  v1_3_0,
		"1.3":    v1_3_1,
		"1.3.1":  v1_3_1,
		"1.4":    v1_4_0,
		"1.4.0":  v1_4_0,
		"1.5":    v1_5_0,
		"1.5.0":  v1_5_0,
		"1.6":    v1_6_0,
		"1.6.0":  v1_6_0,
		"1.7":    v1_7_0,
		"1.7.0":  v1_7_0,
		"1.8":    v1_8_0,
		"1.8.0":  v1_8_0,
		"1.9":    v1_9_0,
		"1.9.0":  v1_9_0,
		"1.10":   v1_10_0,
		"1.10.0": v1_10_0,
		"1.11":   v1_11_0,
		"1.11.0": v1_11_0,
		"1.12.0": v1_12_0,
		"1":      v1_12_2,
		"1.12":   v1_12_2,
		"1.12.1": v1_12_2,
		"1.12.2": v1_12_2,
		"8.0":    v8_0_1,
		"8.0.0":  v8_0_1,
		"8.0.1":  v8_0_1,
		"8.1":    v8_1_0,
		"8.1.0":  v8_1_0,
		"8.2.0":  v8_2_0,
		"8.2":    v8_2_1,
		"8.2.1":  v8_2_1,
		"8.3.0":  v8_3_0,
		"8.3":    v8_3_1,
		"8.3.1":  v8_3_1,
		"8.4":    v8_4_0,
		"8.4.0":  v8_4_0,
		"8.5.0":  v8_5_1,
		"8.5.1":  v8_5_1,
		"8.5":    v8_5_2,
		"8.5.2":  v8_5_2,
		"8.6.0":  v8_6_0,
		"8.6":    v8_6_1,
		"8.6.1":  v8_6_1,
		"8.7":    v8_7_0,
		"8.7.0":  v8_7_0,
		"8.8":    v8_8_0,
		"8.8.0":  v8_8_0,
		"8.9":    v8_9_0,
		"8.9.0":  v8_9_0,
		"8.10":   v8_10_0,
		"8.10.0": v8_10_0,
		"8.11":   v8_11_0,
		"8.11.0": v8_11_0,
		"8.16":   v8_16_0,
		"8.16.0": v8_16_0,
		"8":      v8_17_0,
		"8.17":   v8_17_0,
		"8.17.0": v8_17_0,
	}
)
